version: '3.8'

services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # Serviço para o Redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Serviço para a aplicação Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/subscription_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

# Volumes para persistência de dados
volumes:
  postgres_data:
  redis_data: